sudo: required
services:
  - docker
env: SH="docker exec -t container bash -c"

before_install:
  - docker run -d --name container -v $(pwd):/travis -w /travis yaqwsx/pandoc tail -f /dev/null
  - docker ps

script:
  - $SH "make web"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: build-web
  on:
    branch: master
  verbose: true
